// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geoewhysowfvagxcglmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdlb2V3aHlzb3dmdmFneGNnbG1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODI0OTcsImV4cCI6MjA2NTQ1ODQ5N30.4BujyW-sYg55-x0FGTZ-eC4f26uJbBaR35VZ22rFZbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);